version: "3.7"
services:
  backbone:
    image: nmshd-backbone
    container_name: backbone
    hostname: backbone
    build:
      context: .
      dockerfile: Backbone.API/Dockerfile.debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80
      
      - Modules__Devices__Infrastructure__AzureNotificationHubs__ConnectionString=${ENMESHED_AZURE_NOTIFICATION_HUB_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (Endpoint=sb://<namespace-name>.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=<shared-access-key>)
      - Modules__Devices__Infrastructure__BlobStorage__ConnectionInfo=${ENMESHED_AZURE_NOTIFICATION_HUB_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (Endpoint=sb://<namespace-name>.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=<shared-access-key>)
      
      - Modules__Files__Infrastructure__BlobStorage__ConnectionInfo=${ENMESHED_BLOB_STORAGE_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (DefaultEndpointsProtocol=https;AccountName=<account-name>;AccountKey=<account-key>;EndpointSuffix=core.windows.net)
      
      - Modules__Messages__Infrastructure__BlobStorage__ConnectionInfo=${ENMESHED_BLOB_STORAGE_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (DefaultEndpointsProtocol=https;AccountName=<account-name>;AccountKey=<account-key>;EndpointSuffix=core.windows.net)
      
      - Modules__Relationships__Infrastructure__BlobStorage__ConnectionInfo=${ENMESHED_BLOB_STORAGE_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (DefaultEndpointsProtocol=https;AccountName=<account-name>;AccountKey=<account-key>;EndpointSuffix=core.windows.net)
      
      - Modules__Synchronization__Infrastructure__BlobStorage__ConnectionInfo=${ENMESHED_BLOB_STORAGE_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (DefaultEndpointsProtocol=https;AccountName=<account-name>;AccountKey=<account-key>;EndpointSuffix=core.windows.net)
      
      - Modules__Tokens__Infrastructure__BlobStorage__ConnectionInfo=${ENMESHED_BLOB_STORAGE_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (DefaultEndpointsProtocol=https;AccountName=<account-name>;AccountKey=<account-key>;EndpointSuffix=core.windows.net)

    ports:
      - "127.0.0.10:80:80"
      - "5000:80"
    depends_on:
      - ms-sql-server
      - rabbitmq
    volumes:
      - ./appsettings.override.json:/app/appsettings.override.json
      - .:/usr/app
      
  devices:
    image: bkb-devices
    container_name: bkb-devices
    hostname: devices
    build:
      context: ./Modules/Devices
      dockerfile: Devices.API/Dockerfile.debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80

      - ApplicationInsights__Enabled=false

      - ApplicationOptions__Pagination__DefaultPageSize=50
      - ApplicationOptions__Pagination__MaxPageSize=200
      - ApplicationOptions__AddressPrefix=id1
      
      - AuthenticationConfiguration__IssuerUri=https://devices
      - AuthenticationConfiguration__PublicOrigin=http://localhost:5020
      - Authentication__ValidIssuer=https://devices

      - AzureNotificationHubs__ConnectionString=${ENMESHED_AZURE_NOTIFICATION_HUB_CONNECTION_STRING} # set this environment variable on your local system to an appropriate value (Endpoint=sb://<namespace-name>.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=<shared-access-key>)
      - AzureNotificationHubs__HubName=nh-dev
      
      - CORS__AllowedOrigins=http://localhost:5000;https://editor.swagger.io

      - SqlDatabase__ConnectionString=Server=ms-sql-server;Database=enmeshed;User Id=devices;Password=Passw0rd;TrustServerCertificate=True

      - EventBus__Vendor=RabbitMQ
      - EventBus__RabbitMQUsername=guest
      - EventBus__RabbitMQPassword=guest
      - EventBus__ConnectionInfo=rabbitmq
      
      - JwtOptions__LifetimeInSeconds=14400 # 4h
      - JwtOptions__SigningCertificateSource=file # possible values: {file,config}; when "config" is set, then JwtSigningCertificate__Certificate has to be set to base64 representation of certificate

    ports:
      - "127.0.0.3:80:80"
      - "5020:80"
    depends_on:
      - ms-sql-server
      - rabbitmq
    volumes:
      - ./Modules/Devices:/usr/app

  ### infrastructure ###

  #azure-storage-emulator:
  #  container_name: azure-storage-emulator
  #  image: mcr.microsoft.com/azure-storage/azurite #replacement for Microsoft image, which only runs on windows; source: https://github.com/arafato/azurite
  #  command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0"
  #  ports:
  #    - "10000:10000"
  #  volumes:
  #    - azure-storage-emulator-volume:/data

  ms-sql-server:
    container_name: bkb-mssql_server
    hostname: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - mssql-server-volume:/var/opt/mssql
    ports:
      - 1433:1433

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # mgmt plugin, "guest/guest"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq # default data dir

volumes:
  rabbitmq-volume:
  mssql-server-volume:
    external: true
  #azure-storage-emulator-volume:
  #  external: true
  elastic_data:
