version: "3.7"
services:
  backbone:
    image: nmshd-backbone
    container_name: backbone
    hostname: backbone
    build:
      context: .
      dockerfile: Backbone.API/Dockerfile.debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80

      #- ApplicationInsights__Enabled=false

      #- Authentication__JwtSigningCertificate=MIIDazCCAlOgAwIBAgIUEIiSlffGvbWX64L2TevPqp2Me7swDQYJKoZIhvcNAQELBQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMTA1MjAxMTAyNDhaFw0zMTA1MTgxMTAyNDhaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXgWRymp7sxTNlmCh7XL4Y5FqsqvGMw/LnTMR9ki6Ht87essqI1wUUKFT8+snQ6W2YjvVw0b1b++RrrOJADE3mipPck2Efikvnjszw+Nkyhb6Hh3+2koFE8Jfxoxq7beD/VbAYVl1fKwGRhSUHJvCybnIM7s3svTw+BOj1WFvDfUM3qkYKyarxrywU8bmT4rdE2Xbtyhag7Z8Ngy2jJoNAQhOBH4haV3m97X2fwnh3fFINCWf/j4TzGRj/U3EHe5pDnSZzWv427b+N7JYuSQWoKYPBPiNB5zzzqT1Ifk2+DM7q0wOWoUexJHRxyGPr/Zo1owpI3NnUBHgO0wHS7dkPAgMBAAGjUzBRMB0GA1UdDgQWBBQyyL+oBj25CTXI3v61o+64tbEIKzAfBgNVHSMEGDAWgBQyyL+oBj25CTXI3v61o+64tbEIKzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCfhwUrgC8fwH7msMBwdZM9Fy95uBk/Ao6+WYSQrTP5EX4TfdWs087T7fEdl0MTOuMYgGJlXa5s9pEIwYoaRu5LEPUZ9YDfvpt3J62SgSdEADGImejQzOHSF0DDYNet5HwtnNRVnW2rV6haIay0A+P58mud1TxQXafMww+VkKBnQPY8ArNf59DJXGQduxRTrUE/Unu5UHcucgzUP8962OpUjIA5mQw5D1clZMllTZVc0R3eTcneH2g9rKzwGhpi6yx+1tvcULVEbKx3duZd2rpW9sH6mO7HoeJzGMUmWt4vSoi814ThPwrBIuvpiYabFDaVyUsVaSBCs7iTzzOjNaW8
      #- Authentication__ValidIssuer=http://backbone

      #- CORS__AllowedOrigins=${CORS__ALLOWED_ORIGINS}
      #- CORS__ExposedHeaders=${CORS__EXPOSED_HEADERS}

      #- EventBus__Vendor=RabbitMQ
      #- EventBus__ConnectionInfo=rabbitmq
      #- EventBus__RabbitMQUsername=guest
      #- EventBus__RabbitMQPassword=guest
      #- EventBus__ProjectId = ${GOOGLE_CLOUD_PUBSUB_PROJECT_ID}
      #- EventBus__TopicName=${GOOGLE_CLOUD_PUBSUB_TOPIC_NAME}

      #- SqlDatabase__ConnectionString=Server=ms-sql-server;Database=enmeshed;User Id=challenges;Password=Passw0rd;TrustServerCertificate=True
    ports:
      - "127.0.0.10:80:80"
      - "5000:80"
    depends_on:
      - ms-sql-server
      - rabbitmq
    volumes:
      - ./appsettings.override.json:/app/appsettings.override.json
      - .:/usr/app

  ### infrastructure ###

  #azure-storage-emulator:
  #  container_name: azure-storage-emulator
  #  image: mcr.microsoft.com/azure-storage/azurite #replacement for Microsoft image, which only runs on windows; source: https://github.com/arafato/azurite
  #  command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0"
  #  ports:
  #    - "10000:10000"
  #  volumes:
  #    - azure-storage-emulator-volume:/data

  ms-sql-server:
    container_name: bkb-mssql_server
    hostname: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - mssql-server-volume:/var/opt/mssql
    ports:
      - 1433:1433

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # mgmt plugin, "guest/guest"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq # default data dir

volumes:
  rabbitmq-volume:
  mssql-server-volume:
    external: true
  #azure-storage-emulator-volume:
  #  external: true
  elastic_data:
