apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.sendidentitydeletionreminders.name }}
spec:
  schedule: {{ .Values.sendidentitydeletionreminders.schedule }}
  jobTemplate:
    metadata:
      {{- with .Values.sendidentitydeletionreminders.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.sendidentitydeletionreminders.name }}
    spec:
      restartPolicy: Never
      {{- with .Values.sendidentitydeletionreminders.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sendidentitydeletionreminders.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: settings-override
          configMap:
            name: configuration
      containers:
        - name: {{ .Values.sendidentitydeletionreminders.name }}
          {{- with .Values.sendidentitydeletionreminders.securityContext }}
          securityContext:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          resources:
            {{- toYaml .Values.sendidentitydeletionreminders.resources | nindent 12 }}
          image: "{{ .Values.sendidentitydeletionreminders.image.repository }}:{{- default .Chart.AppVersion .Values.sendidentitydeletionreminders.image.tagOverride }}"
          imagePullPolicy: {{ .Values.sendidentitydeletionreminders.image.pullPolicy }}
          volumeMounts:
            - name: settings-override
              mountPath: /app/appsettings.override.json
              subPath: appsettings.override.json
              readOnly: true
          env:
            {{- with .Values.sendidentitydeletionreminders.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.sendidentitydeletionreminders.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sendidentitydeletionreminders.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sendidentitydeletionreminders.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
